name: ShadowCrestModeration
version: 1.1.1
main: de.shadowcrest.mod.ShadowCrestMod
api-version: 1.21

author: ShadowCrest

commands:
  warn:
    usage: /warn <spieler> <grund...>
  kick:
    usage: /kick <spieler> <grund...>
  ban:
    usage: /ban <spieler> <grund...>
  tempban:
    usage: /tempban <spieler> <dauer> <grund...>
  ipban:
    usage: /ipban <spieler|ip> <grund...>
  scm:
    usage: /scm reload|info|accept|tpticket|tickets|close|gui
  unban:
    usage: /unban <spieler>
  unipban:
    usage: /unipban <ip>
  clearwarns:
    usage: /clearwarns <spieler>
  warns:
    usage: /warns <spieler>
  ip:
    usage: /ip <spieler>
  playtime:
    usage: /playtime <spieler>
  ticket:
    usage: /ticket







permissions:
  shadowcrest.mod.warn:
    default: op
  shadowcrest.mod.kick:
    default: op
  shadowcrest.mod.ban:
    default: op
  shadowcrest.mod.tempban:
    default: op
  shadowcrest.mod.ipban:
    default: op
  shadowcrest.mod.notify:
    default: op
  shadowcrest.mod.reload:
    default: op
  shadowcrest.mod.info:
    default: op
  shadowcrest.mod.unban:
    default: op
  shadowcrest.mod.unipban:
    default: op
  shadowcrest.mod.clearwarns:
    default: op
  shadowcrest.mod.warns:
    default: op
  shadowcrest.mod.playtime:
    default: op
  shadowcrest.mod.ticket.notify:
    default: op
  shadowcrest.mod.ticket.accept:
    default: op
  shadowcrest.mod.ticket.tp:
    default: op
  shadowcrest.mod.ticket.list:
    default: op
  shadowcrest.mod.ticket.close:
    default: op
  shadowcrest.mod.ticket.staff:
    default: op





